# Generated by Django 5.0.6 on 2024-06-30 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singerinfo', '0002_singer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singerinfo.singer'),
        ),
    ]
