# Generated by Django 5.0.6 on 2024-07-07 14:59

import singerinfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singerinfo', '0005_tag_singer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=singerinfo.models.image_upload_path),
        ),
    ]
